PR2022-146 Layout of all boards
NKonstantin007/kanban-internship pull request #19
Opened 2022-02-18 07:06 UTC by NIBELUNG123

Add all board

2022-02-18 14:48 UTC, Neoclassic-alt requested changes
The layout looks ugly. I have given several advices, how make this layout better.

**After/before**

![Screenshot_68](https://user-images.githubusercontent.com/64008440/154705036-3071c455-3dca-4cf0-9f9b-0e2a68a728b8.png)
![Screenshot_69](https://user-images.githubusercontent.com/64008440/154705043-4e62c885-90d8-45c2-8241-b69e63e75724.png)

2022-02-18 14:48 UTC, Neoclassic-alt commented on src/modules/Boards/components/AddCard.tsx
> +            height="419px"
Delete height property

2022-02-18 14:48 UTC, Neoclassic-alt commented on src/modules/Boards/components/AddCard.tsx
> +            <Typography color="#1d1d1d" variant="h1">
Delete sign +. May be add icon "Plus" like AddCircle ([Example](https://github.com/NKonstantin007/kanban-internship/blob/master/src/modules/Project/components/AddNewProjectCard.tsx))

2022-02-21 01:27 UTC, VKhayretdinov requested changes

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/AddCard.tsx
> +    <Card sx={{ maxWidth: 345 }} style={{ backgroundColor: '#fefefe' }}>
Both props used for setting styles ⇾ use one of them. I suggest move color to a constant. I'm sure that this color will be used in other part of the project

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/AddCard.tsx
> +            <Typography color="#1d1d1d" variant="h6">
Move color to a constant. I think you already have a file for colors constants

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/Boards.tsx
> +export function Boards() {
```suggestion
export function Boards(): React.FC {
```

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/Boards.tsx
> +      background-color="#121212"
move color to a constant

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/Boards.tsx
> +        width="1075px"
Why do you use fixed width here? Just make it adaptive

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/Boards.tsx
> +        grid-gap="20px"
@Neoclassic-alt Why  do you prefer flex?

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/Boards.tsx
> +          return (
I think it's not necessary

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/Boards.tsx
> +            >
Just let name it as BoardCard. Also, you should check the opportunity to create shared card for projects page and boards page

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/Boards.tsx
> +                height="194"
```suggestion
                height="195"
```

And please discuss adaptivity of your project with your team

2022-02-21 01:27 UTC, VKhayretdinov commented on src/modules/Boards/components/Boards.tsx
> +                  Принимает участие {item} пользователей
Use single language in your project, please

2022-02-27 15:05 UTC, closed without merging

2022-02-27 15:05 UTC, Neoclassic-alt commented
Not actual